CREATE TABLE characters (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    story_id INTEGER REFERENCES stories(id) NOT NULL,
    name TEXT NOT NULL,
    age TEXT,
    description TEXT,
    gender TEXT,
    appearance TEXT,
    fashion TEXT,
    room_decor TEXT
)