CREATE TABLE story_bits_characters (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    story_id INTEGER REFERENCES story_bits_stories(id),
    name TEXT NOT NULL,
    age TEXT,
    description TEXT,
    gender TEXT,
    appearance TEXT,
    fashion TEXT,
    room_decor TEXT
)