CREATE TABLE story_bits_settings (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    story_id INTEGER REFERENCES story_bits_stories(id) NOT NULL,
    name TEXT NOT NULL,
    isResidence BOOLEAN DEFAULT 'false',
    decor TEXT
)