CREATE TABLE settings (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    story_id INTEGER REFERENCES stories(id) NOT NULL,
    name TEXT NOT NULL,
    is_residence BOOLEAN DEFAULT 'false',
    decor TEXT
)