CREATE TABLE residences (
    character_id INTEGER REFERENCES characters(id) ON DELETE CASCADE,
    setting_id INTEGER REFERENCES settings(id) ON DELETE CASCADE,
    PRIMARY KEY (character_id, setting_id),
    id iNTEGER GENERATED BY DEFAULT AS IDENTITY
);

INSERT INTO residences (character_id, setting_id)
VALUES
    (2, 1),
    (3, 1),
    (4, 2),
    (5, 2),
    (15, 14),
    (6, 4),
    (7, 5),
    (8, 6),
    (16, 6),
    (9, 7),
    (10, 8),
    (11, 9),
    (12, 10),
    (13, 11),
    (14, 12);